-- ---------------------------------------------------------------------------
-- Auto-init wrapper for a FRESH Oracle XE container.
--
-- The official Oracle image runs each *.sql in /opt/oracle/scripts/setup ONCE,
-- right after the database is created, connected as SYSDBA to the CDB root ($XE).
-- Our schemas live in the XEPDB1 pluggable database, so this wrapper switches
-- into XEPDB1 and runs the HSS setup scripts in the correct order.
--
-- The numbered scripts are mounted read-only at /opt/oracle/hss-scripts (NOT in
-- the setup dir) so the image doesn't try to run them individually in the wrong
-- container. See docker-compose.yml.
--
-- (If you switch to the community gvenzl/oracle-xe image, mount this file into
--  /container-entrypoint-initdb.d instead.)
-- ---------------------------------------------------------------------------

-- SET DEFINE OFF is essential: seed/data scripts may contain '&' which sqlplus
-- would otherwise treat as a substitution variable and hang the container.
SET DEFINE OFF
SET SQLBLANKLINES ON
-- Keep going if an individual statement fails (setup runs once; be resilient).
WHENEVER SQLERROR CONTINUE

ALTER SESSION SET CONTAINER = XEPDB1;

PROMPT ===== 1_create_schemas.sql =====
@/opt/oracle/hss-scripts/1_create_schemas.sql
PROMPT ===== 2_table_data_bkp.sql (tables + seed roles/permissions) =====
@/opt/oracle/hss-scripts/2_table_data_bkp.sql
PROMPT ===== 3_db_objects_bkp.sql (views/sequences/procedures) =====
@/opt/oracle/hss-scripts/3_db_objects_bkp.sql

-- Objects/triggers now exist. Sync identities BEFORE the trigger-firing dummy
-- load so the audit triggers (which write to EVENTS/_REV via identity) don't
-- collide with the explicit-ID rows seeded above (ORA-00001).
PROMPT ===== resyncing identities (pre-seed) =====
BEGIN
  FOR r IN (SELECT owner, table_name, column_name, generation_type
              FROM all_tab_identity_cols
             WHERE owner IN ('GENERAL','DENTAL','MIDWIFERY','HIPMA','CONSTELLATION_HEALTH')) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE "'||r.owner||'"."'||r.table_name||'" MODIFY "'||r.column_name||
        '" GENERATED '||r.generation_type||' AS IDENTITY START WITH LIMIT VALUE';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

PROMPT ===== 4_dummy_table_data.sql (dev sample data; delete this line for non-dev) =====
@/opt/oracle/hss-scripts/4_dummy_table_data.sql
PROMPT ===== phase_2.sql =====
@/opt/oracle/hss-scripts/phase_2.sql
PROMPT ===== dental-release2.sql =====
@/opt/oracle/hss-scripts/dental-release2.sql
PROMPT ===== DENTAL-Check-all-coverage.sql (DENTAL_SERVICE_COVERAGE + detail view/trigger) =====
@/opt/oracle/hss-scripts/DENTAL-Check-all-coverage.sql
PROMPT ===== 99_seed_admin_user.sql =====
@/opt/oracle/hss-scripts/99_seed_admin_user.sql

COMMIT;

-- Seed data inserts rows with explicit IDs into GENERATED BY DEFAULT AS IDENTITY
-- columns, which does NOT advance the identity generator — so the next app/trigger
-- insert generates ID=1 and collides (ORA-00001). Resync every identity to max+1.
PROMPT ===== resyncing identity columns =====
BEGIN
  FOR r IN (SELECT owner, table_name, column_name, generation_type
              FROM all_tab_identity_cols
             WHERE owner IN ('GENERAL','DENTAL','MIDWIFERY','HIPMA','CONSTELLATION_HEALTH')) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE "'||r.owner||'"."'||r.table_name||'" MODIFY "'||r.column_name||
        '" GENERATED '||r.generation_type||' AS IDENTITY START WITH LIMIT VALUE';
    EXCEPTION WHEN OTHERS THEN NULL; -- empty table / already synced: leave as-is
    END;
  END LOOP;
END;
/

-- Objects are exported in dependency-agnostic order (e.g. views defined before
-- the functions they call), so some compile INVALID on first pass. Recompile
-- every schema now that all objects + grants exist, so the build ends clean.
PROMPT ===== recompiling schemas =====
BEGIN
  FOR s IN (SELECT username FROM dba_users
             WHERE username IN ('GENERAL','DENTAL','MIDWIFERY','HIPMA','CONSTELLATION_HEALTH')) LOOP
    DBMS_UTILITY.COMPILE_SCHEMA(schema => s.username, compile_all => FALSE);
  END LOOP;
END;
/

PROMPT ===== HSS schema init complete =====
