import express, { Request, Response, Router } from "express";
import cors from "cors";
import helmet from "helmet";
import path from 'path';
import { userRouter, constellationRouter, midwiferyRouter, hipmaRouter, generalRouter, dentalRouter } from "./routes";
import * as config from './config';
import { doHealthCheck } from "./utils/healthCheck";
import { configureAuthentication } from "./routes/auth"

const app = express();
const sufixPath = '/index.html';
const routes: Record<string, Router> = {
  "/api/user": userRouter,
  "/api/constellation": constellationRouter,
  "/api/midwifery": midwiferyRouter,
  "/api/hipma": hipmaRouter,
  "/api/general": generalRouter,
  "/api/dental": dentalRouter
};

// --- Rate limiting: mounted BEFORE the routes so it actually protects them
// (it was previously registered after the routers, where it had no effect).
// A single realistic per-IP ceiling replaces the old 5000/min (~unlimited).
const RateLimit = require('express-rate-limit');
app.use(RateLimit({
  windowMs: 1 * 60 * 1000, // 1 minute
  max: 600,                // per-IP request ceiling
  standardHeaders: true,
  legacyHeaders: false,
}));

// --- Body parsing: a small global limit, with a larger limit applied ONLY to
// the file-upload endpoints (citizen intake /store + dental /update). The first
// matching body parser wins, so large bodies are accepted only on these paths.
const uploadPaths = [
  "/api/dental/store",
  "/api/hipma/store",
  "/api/midwifery/store",
  "/api/constellation/store",
  "/api/dental/update",
];
app.use(uploadPaths, express.json({ limit: "25mb" }));
app.use(uploadPaths, express.urlencoded({ extended: true, limit: "25mb" }));
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true, limit: "1mb" }));

// --- Security headers: full helmet(), with the existing CSP configured through it.
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      'default-src': [ "'self'" ],
      'base-uri': [ "'self'" ],
      'block-all-mixed-content': [],
      'font-src': [ "'self'", 'https:', 'data:' ],
      'frame-ancestors': [ "'self'" ],
      'img-src': [ "'self'", 'data:' ],
      'object-src': [ "'none'" ],
      'script-src': [ "'self'" ],
      'script-src-attr': [ "'none'" ],
      'style-src': [ "'self'", 'https:', "'unsafe-inline'" ]
    },
  },
}));

// very basic CORS setup
app.use(cors({
  origin: config.FRONTEND_URL,
  optionsSuccessStatus: 200,
  credentials: true
}));

configureAuthentication(app);

app.get("/api/healthCheck", (req: Request, res: Response) => {
  doHealthCheck(res);
});

// Adding routes.
for (const url in routes) {
  app.use(url, routes[url]);
}

/*if (config.NODE_ENV !== "production")
  baseWebPath = "/dist/web";
*/
// serves the static files generated by the front-end
app.use(express.static(path.join(__dirname, "web")));

// if no other routes match, just send the front-end
app.use((req: Request, res: Response) => {
  res.sendFile(path.join(__dirname, "web") + sufixPath)
})

app.listen(config.API_PORT, () => {
  console.log(`API listenting on port ${config.API_PORT}`);
});
